spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/shiro_demo?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC
      username: root
      password: 123123
      max-active: 20
      max-wait: 5000
      initial-size: 1
      filters: stat,log4j,wall
      validationQuery: SELECT 'x'   #验证连接
      enable: true

      stat-view-servlet:
        enabled: true
        login-username: root
        login-password: 123123
        allow:
        deny:
        url-pattern: /druid/*

  thymeleaf:
    cache: false
    enabled: true

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations:
    classpath:mapper/*Mapper.xml

shiro:
    hash-algorithm-name: md5
    hash-iterations: 2
    anon-urls:
      - /index.html*
      - /login/toLogin*
      - /login/login*
    log-out-url: /login/logout*
    authc-urls: /**
    login-url: /index.html



